### PR TITLE
Fix the kill functionality in JT

### PR DESCRIPTION
**Pull request by tchow-stripe**
We need recentJobClient to expose the RM address so we can use the yarn REST api.

r? @abdul-stripe @dug-stripe 
cc? @stripe/data-platform

### CODE REVIEW

**Comment by abull-stripe** [comment]
lgtm

I would test against multiple clusters on edge mcjobtracker if you havn't

**Comment by abdul-stripe** [comment]
ahh good catch. i missed this in my previous refactor. in fact, all of `rm`, `hs`, `ps` and `namenodeAddress` got moved out of `jobtracker.go` and should deleted from the struct.

thanks for fixing this! i'll follow up with the rest of it after this is merged

**Comment by tchow-stripe** [comment]
re-r? @abull-stripe

**Comment by abull-stripe** [comment]
lgtm

**Pull request merged**
