### PR TITLE
Confirm before killing job

### PR DESCRIPTION
**Pull request by forklady42**
r? @jbalogh

### CODE REVIEW

**Comment by jbalogh** [comment]
oooh can you add a screenshot of what this looks like?

**Comment by forklady42** [comment]
screen shot 2016-03-08 at 8 31 32 am

Happy to take suggestions on wording.

**Comment by jbalogh** [comment]
Can we make the box tighter so there's not so much empty space?

**Comment by forklady42** [comment]
more like this? or also want the white space around the buttons tightened?

screen shot 2016-03-08 at 10 15 21 am

**Comment by jbalogh** [comment]
:+1: that's tight

**Pull request merged**
